### PR TITLE
Fixing primitive procedures

### PR DESCRIPTION
**Pull request by rodri042**
Fixes https://github.com/mumuki/mumuki-laboratory/issues/1050

Setting primitiveProcedures again when toolbox is updated

### CODE REVIEW

**Comment by flbulgarelli** [comment]
Awesome! Does this fix https://github.com/mumuki/mumuki-laboratory/issues/1050, right?

**Comment by rodri042** [comment]
> Awesome! Does this PR fix mumuki/mumuki-laboratory#1050, right?

Yes, it fixes that issue

**Comment by flbulgarelli** [comment]
@luchotc please review and merge

**Comment by flbulgarelli** [comment]
> The only observation i can make is that we are using set/get name convention for methods, so maybe defineTeacherActions should be setTeacherActions, but it's your call

@rodri042 could you change it and merge it, please?

**Pull request merged**
