### PR TITLE
Custom editor

### PR DESCRIPTION
**Pull request by rodri042**
Related issue: https://github.com/mumuki/mumuki-laboratory/issues/898

### CODE REVIEW

**Comment by flbulgarelli** [comment]
Please use mumuki.load instead of jQuery onready

**Comment by flbulgarelli** [comment]
The rest is fine

**Comment by rodri042** [comment]
> It doesn't work with `mumuki.load` because the `<gs-element-blockly />` is inserted dynamically through the runner's javascript.

**Comment by flbulgarelli** [comment]
> It doesn't work with mumuki.load because the <gs-element-blockly /> is inserted dynamically through the runner's javascript.

OK. However please take into account that turbolinks in rails modifies the way assets are loaded. We should just recheck that everything works both on first load of the page an after reloading it.

**Pull request merged**
