### PR TITLE
Failing spec - Closes #19

### LINKED ISSUE #19: Test with expectations not working
In branch https://github.com/mumuki/mumuki-gobstones-runner/tree/failing_spec i added an example test.
The problem: 

> undefined method `value' for nil:NilClass in /var/lib/gems/2.3.0/gems/mumukit-inspection-3.1.0/lib/mumukit/inspection/expectation.rb:68

### PR DESCRIPTION
**Pull request by rodri042**
Diffs in: https://github.com/mumuki/mumuki-gobstones-runner/compare/failing_spec%5E...failing_spec

I think the test's expectations were syntactically incorrect. I updated them using the new mulang syntax (@flbulgarelli is that right?)

### CODE REVIEW

**Comment by flbulgarelli** [comment]
Hi! Not really, runners are supposed to support both old v0 and new v2 formats. So the original test is correct

**Comment by flbulgarelli** [comment]
Actually Mumukit Inspection is capable of handling both them, are you parsing them by hand?

**Comment by rodri042** [comment]
Hmm... I'm only parsing the AST, not the expectations, here: https://github.com/mumuki/mumuki-gobstones-runner/blob/master/lib/expectations_hook.rb#L22

The error happens in `mumukit/inspection/expectation.rb`:
```rb
    def as_v2
      if has? 'Binding' then as_v2_declare ''
      elsif has? 'TypeDeclaration' then as_v2_declare 'TypeAlias'
      elsif has? 'TypeSignature' then as_v2_declare 'TypeSignature'
      elsif has? 'Variable' then as_v2_declare 'Variable'
      elsif has? 'Arity' then as_v2_declare "ComputationWithArity#{inspection.target.value}"
      elsif has? 'DirectRecursion' then as_v2_declare "Recursively"
      elsif has? 'Usage'
        # here `inspection` is a string, it doesn't have `target`
        V2.new binding, new_inspection('Uses', Mumukit::Inspection::Target.named(inspection.target.value))
      else as_v2_use
      end
    end
```

**Comment by rodri042** [comment]
Ok, so we need retrocompatibility with the old syntax. Closing this for now...

**Pull request closed without merging**
