### PR TITLE
Using new stones assets - Fixes mumuki/mumuki-laboratory#1184

### PR DESCRIPTION
**Pull request by rodri042**
Fixes https://github.com/mumuki/mumuki-laboratory/issues/1184

screenshot2

### CODE REVIEW

**Comment by flbulgarelli** [comment]
Awesome! However, is it just my imagination or balls are getting cropped?

**Comment by rodri042** [comment]
The problem is that the red outline of the current cell is behind the stones... it happens in `master` too:

screenshot1

With a 1px outline (instead of 3px) looks a bit cleaner but I don't know if it's the best...
screenshot3

**Comment by flbulgarelli** [comment]
Got it. @cucusita?

**Comment by flbulgarelli** [comment]
@rodri042: @cucusita says it is fine, but that the font should be Nunito Bold, not just plain Nunito.

**Comment by rodri042** [comment]
@flbulgarelli done!

**Pull request merged**
